package com.itbuzzpress.chapter2.wsdemo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-09-03T13:21:30.139+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://wsdemo.chapter2.itbuzzpress.com/", name = "Customer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Customer {

    @WebResult(name = "CustomerRecord", targetNamespace = "http://wsdemo.chapter2.itbuzzpress.com/", partName = "CustomerRecord")
    @WebMethod
    public CustomerRecord locateCustomer(
        @WebParam(partName = "FirstName", name = "FirstName")
        java.lang.String firstName,
        @WebParam(partName = "LastName", name = "LastName")
        java.lang.String lastName,
        @WebParam(partName = "Address", name = "Address")
        USAddress address
    );
}
