package com.itbuzzpress.chapter2.wsdemo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-09-03T13:21:30.183+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "CustomerService", 
                  wsdlLocation = "http://localhost:8080/ws-demo-wsdl-1.0/CustomerService?wsdl",
                  targetNamespace = "http://wsdemo.chapter2.itbuzzpress.com/") 
public class CustomerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsdemo.chapter2.itbuzzpress.com/", "CustomerService");
    public final static QName CustomerPort = new QName("http://wsdemo.chapter2.itbuzzpress.com/", "CustomerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws-demo-wsdl-1.0/CustomerService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws-demo-wsdl-1.0/CustomerService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Customer
     */
    @WebEndpoint(name = "CustomerPort")
    public Customer getCustomerPort() {
        return super.getPort(CustomerPort, Customer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Customer
     */
    @WebEndpoint(name = "CustomerPort")
    public Customer getCustomerPort(WebServiceFeature... features) {
        return super.getPort(CustomerPort, Customer.class, features);
    }

}
